spring.application.name=CacheMicroservice
spring.datasource.url=jdbc:sqlite:cache.db
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=student
spring.rabbitmq.password=student

cacheapp.rabbitmq.exchange=cache.direct

cacheapp.rabbitmq.routingkey.command=cache.routingkey.command
cacheapp.rabbitmq.routingkey.file=cache.routingkey.file

cacheapp.rabbitmq.queue.state=cache.queue.state
cacheapp.rabbitmq.queue.query=cache.queue.query

server.port=8081