spring.datasource.url=jdbc:sqlite:/home/moni/Documents/Sisteme-Distribuite/Lab9-SD/exemplul 2/Client/client.db
spring.jpa.database-platform=org.sqlite.hibernate.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=update
server.port=8080