spring.datasource.url=jdbc:sqlite:books.db
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=student
spring.rabbitmq.password=student

spring.rabbitmq.exchange=cache.direct

libraryapp.rabbitmq.queue.command=cache.queue.command
libraryapp.rabbitmq.queue.file=cache.queue.file

libraryapp.rabbitmq.routingKey.state=cache.routingkey.state
libraryapp.rabbitmq.routingKey.query=cache.routingkey.query

